### ISSUE TITLE
Small Fix For Automation Trigger

### ISSUE THREAD

**Issue by salonluden** [idodov/RedAlert#4]
Thanks for this amazing project. Just a small fix for the automation trigger: it's better to remove the `to: "on"` (and add it as a condition, if necessary) as it will only update if the state changes and not any attributes change. For example, if you are looking to check if your city has a red alert through the automation, and there was a red alert previously in a different area the automation will not run when the area attribute changes but the state stays on.

**Comment by idodov** [comment]
Hi @salonluden
Thank you for your support and kind words!

Within the automation examples I've shared here, the initial one demonstrates how to set up triggers for **alerts occurring anywhere**, while the second illustrates the automation of tasks tailored to a **specific city**.

These examples are provided to ensure that users are well-equipped to manage triggers for their desired scenarios.
