### ISSUE TITLE
Just a thank you

### ISSUE THREAD

**Issue by ofirsnb** [idodov/RedAlert#5]
Hi Idodov,

Just wanted to say thank you for this awesome script and idea!

I live on the 1st floor in our building,   and I've put a large led-matrix on the balcony,
and I've been using your script to display the entrance's code to our building,  for bystanders to be able to get inside the shelter when there's a Red-Alert.

Very cool, working great so far,  thanks again and stay safe 🙏

**Comment by idodov** [comment]
I appreciate your kind words and support! Consider using a fingerbot for the project to keep the code hidden from strangers.
